kind: Service
apiVersion: v1
metadata:
  namespace: calc
  name: calc
spec:
  selector:
    app: calc
  type: LoadBalancer
  ports:
  - name: server
    protocol: TCP
    port: 80
    targetPort: 8080
